# Generated by Django 5.2.4 on 2025-07-11 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carro',
            name='dono',
        ),
        migrations.RemoveField(
            model_name='carro',
            name='marca',
        ),
        migrations.RemoveField(
            model_name='post',
            name='carro',
        ),
        migrations.DeleteModel(
            name='Marca',
        ),
        migrations.DeleteModel(
            name='Carro',
        ),
    ]
